// ────────────────────────────────────────────────────────────────
// Bilingual copy. Toggle via langStore.
// ────────────────────────────────────────────────────────────────
const COPY = {
  de: {
    nav: {
      story: "Die Geschichte",
      how: "So funktioniert's",
      chapters: "Alle Abenteuer",
      workshop: "Hinter der Marke",
      folder: "Die Box",
      family: "Für Familien",
      faq: "Fragen",
      contact: "Kontakt",
      shop: "Abenteuer Starten",
      mobile_cta: "Das Abenteuer beginnen",
    },
    announce: "Nur rund 250 Boxen im Monat · Versand in 2–3 Werktagen",
    stickyCta: "In den Warenkorb",
    stickyNote: "inkl. MwSt.",
    stickyAll: "Alle Kapitel",
    trust: { ship: "Lieferung in 2–3 Werktagen", returns: "Versand & Rücksendung", pay: ["PayPal", "Klarna", "SEPA"] },
    exit: { title: "Warte — 10\u202f% auf deine erste Box!", body: "Trag dich in die Reisepost ein und wir schicken dir 10\u202f% Rabatt auf euer erstes Kapitel.", placeholder: "deine@email.de", cta: "Rabatt sichern", success: "Danke! Dein Rabattcode ist unterwegs. 🐻", dismiss: "Nein, danke" },
    bands: [
      { eyebrow: "Los geht's", title: "Bereit, das erste Kapitel zu öffnen?", cta: "Kapitel 1 entdecken", href: "/produkt/kapitel-1-fluesterwald", note: "Nur rund 250 Boxen im Monat · Versand in 2–3 Werktagen" },
      { eyebrow: "Personalisiert", title: "Der Name deines Kindes wartet schon auf Seite 1.", cta: "Abenteuer starten", href: "#chapters", note: "Name im Buch · gravierte Schatzmappe" },
      { eyebrow: "8 Kapitel · 1 verborgener Schatz", title: "Startet euren ersten Abend.", cta: "Kapitel 1 entdecken", href: "/produkt/kapitel-1-fluesterwald", note: "Plastikfreie Verpackung · FSC-Holz" },
    ],

    hero: {
      eyebrow: "Die große Schatzsuche mit Popcorn & Freddy",
      title_a1: "",
      title_a2: "Ein Abenteuer zum Vorlesen, Bauen und ",
      title_a3: "Entdecken",
      title_a4: ".",
      sub_a: "Eine personalisierte Abenteuerreihe in 8 aufeinander aufbauenden Kapiteln. Gemeinsam baut ihr neue Erfindungen, löst Rätsel und begleitet Popcorn & Freddy Schritt für Schritt bis zum verborgenen Schatz.",
      cta_primary: "Kapitel 1 entdecken",
      cta_secondary: "So funktioniert's",
      trust: [
        { icon: "⭐", label: "Name deines Kindes im Buch" },
        { icon: "🧩", label: "Echte Holzspielzeuge zum Bauen" },
        { icon: "❤️", label: "Gemeinsame Familienzeit statt Bildschirmzeit" },
        { icon: "🎈", label: "Ab 4 Jahren" },
      ],

      title_b1: "Bau dir",
      title_b2: " dein eigenes ",
      title_b3: "Märchen.",
      sub_b: "Jede Box ist eine Kapitel-Welt aus Holz: Bauanleitung, Pinsel, Farben und eine Karte zur nächsten Etappe. Lesen, bauen, träumen — gemeinsam.",

      title_c1: "Die Schatzkarte",
      title_c2: " ruft.",
      sub_c: "Folge Popcorn und Freddy über 8 aufeinander aufbauende Kapitel bis zum verborgenen Schatz. Jedes Kapitel ist ein neuer Ort, eine neue Box, ein neues Abenteuer.",
    },

    heroImg: {
      badge: "Personalisiert mit dem Namen deines Kindes",
      sub: "Ein personalisiertes Abenteuer-Vorlesebuch mit dem Namen deines Kindes in allen 8 Kapiteln. Baut ein neues Holzspielzeug, löst Rätsel und findet mit Popcorn & Freddy den verborgenen Schatz.",
      cards: [
        { icon: "user", t: "Der Name deines Kindes im Buch", d: "Personalisiert in jedem Kapitel." },
        { icon: "build", t: "Neue Erfindung in jedem Kapitel", d: "Gemeinsam bauen. Rätseln. Entdecken." },
        { icon: "heart", t: "Eine Schatzsuche für die ganze Familie", d: "8 Abenteuer bis zum verborgenen Schatz." },
      ],
      cta_primary: "Abenteuer starten",
      cta_secondary: "Alle Kapitel",
      facts: "39,90 € · Kein Abo · Ab 4 Jahren",
      mini: [
        { icon: "screen", t: "Bildschirmfreie gemeinsame Zeit" },
        { icon: "build", t: "Lernen beim Spielen" },
        { icon: "book", t: "Dein Kind ist der Held" },
        { icon: "archive", t: "8 Kapitel. Ein Schatz." },
      ],
      below: [
        { icon: "truck", t: "Rund 250 im Monat", d: "Jede von Hand gefertigt" },
        { icon: "shield", t: "Sicher & schadstofffrei", d: "Für Kinder entwickelt" },
        { icon: "gift", t: "Das perfekte Geschenk", d: "Für kleine Abenteurer" },
      ],
    },

    badge: {
      ages: "Ab 4 Jahren",
      eu: "Hergestellt in der EU",
      wood: "FSC-Holz",
      magic: "Mit Magie verpackt",
    },

    story: {
      eyebrow: "Die Geschichte",
      title: "Eine Geschichte, in der dein Kind mitspielt.",
      body: "Als Popcorn und Freddy eine geheimnisvolle Schatzkarte finden, beginnt ihre größte Reise. Doch den verborgenen Schatz finden sie nicht allein. Deshalb wird der Name eures Kindes in jedes Kapitel gedruckt und Teil der Geschichte. Gemeinsam erlebt ihr 8 aufeinander aufbauende Abenteuer, baut hilfreiche Erfindungen, löst Rätsel und begleitet Popcorn & Freddy bis zum großen Schatz.",
      pop_name: "Popcorn",
      pop_role: "der neugierige Bär",
      pop_quote: "„Was steht im nächsten Kapitel?\"",
      pop_desc: "Neugierig, klug und immer auf der Suche nach dem nächsten Hinweis.",
      fred_name: "Freddy",
      fred_role: "der clevere Fuchs",
      fred_quote: "„Ich hab einen Plan!\"",
      fred_desc: "Schlau, mutig und nie um eine Idee verlegen.",
      peter_name: "Dein Kind",
      peter_role: "Die Hauptfigur des Abenteuers",
      peter_quote: "„Welche Farbe nehmen wir?\"",
      peter_desc: "Sein Name steht in jedem Kapitel — aus dem Buch wird seine eigene Schatzsuche.",
    },

    how: {
      eyebrow: "Schritt für Schritt",
      title: "So funktioniert's",
      tagline: "Auspacken. Vorlesen. Bauen. Bewahren.",
      sub: "Vom ersten Klick bis zum Sticker auf der Schatzkarte — so läuft jedes Kapitel ab.",
      steps: [
        { n: "01", icon: "pen", t: "Bestellen & Namen verraten", d: "Ihr bestellt das erste Kapitel und sagt uns den Namen eures Kindes. Mehr müsst ihr nicht tun." },
        { n: "02", icon: "gift", t: "Die persönliche Box kommt an", d: "Darin warten die Mappe mit dem Namen eures Kindes, die große Schatzkarte — und das Kapitel, in dem euer Kind selbst in der Geschichte steht." },
        { n: "03", icon: "book", t: "Gemeinsam lesen", d: "Ihr lest die Geschichte vor — oder euer Kind liest sie euch vor. Popcorn & Freddy nehmen es mit auf die Reise." },
        { n: "04", icon: "build", t: "Rätseln & aus Holz bauen", d: "Mitten im Kapitel bitten Popcorn & Freddy um Hilfe: Ein Rätsel will gelöst und ein Werkzeug aus dem Holzbausatz gebaut werden — nur so geht die Reise am Hindernis weiter." },
        { n: "05", icon: "palette", t: "Bemalen & verzieren", d: "Mit dem beiliegenden Pinsel und kinderfreundlichen Farben bekommt jedes Werkstück seinen eigenen Look." },
        { n: "06", icon: "archive", t: "Sammeln & Sticker kleben", d: "Das Kapitel wandert in die persönliche Mappe, der Sticker kommt auf die Schatzkarte — so seht ihr bei jedem Abenteuer, wie weit ihr schon seid." },
      ],
    },

    map: {
      eyebrow: "Die Reise",
      title: "8 Abenteuer. Ein verborgener Schatz.",
      sub: "Vom Flüsterwald bis zur geheimnisvollen Höhle – jedes Kapitel erzählt ein neues Abenteuer. Gemeinsam helft ihr Popcorn & Freddy, baut Erfindungen für die Reise und folgt der Schatzkarte Schritt für Schritt bis zum verborgenen Schatz.",
      poke: "Tipp: Klick auf die Stationen!",
    },

    why: {
      eyebrow: "Warum Eltern es lieben",
      title: "Schafft Erinnerungen, die ein Leben lang bleiben.",
      sub: "Jedes Kapitel bringt eure Familie zusammen — lesen, bauen, bemalen und rätseln, während euer Kind zum Helden seines eigenen persönlichen Abenteuers wird.",
      items: [
        { t: "Gemeinsame Zeit ohne Bildschirm", tag: "Echte Momente statt Bildschirmzeit.", d: "Statt passiver Bildschirmzeit lesen, bauen und rätseln Kinder und Eltern Seite an Seite — und schaffen Erinnerungen, die bleiben." },
        { t: "Lernen durch Spielen", tag: "Kreativität, Problemlösen & Feinmotorik.", d: "Jedes Kapitel verbindet Geschichte, Bauen und Rätsel — Kinder denken, gestalten und lernen ganz nebenbei, während sie Spaß haben." },
        { t: "Euer Kind ist der Held", tag: "Ein wirklich persönliches Abenteuer.", d: "Der Name eures Kindes zieht sich durch alle acht Kapitel — so wird es Teil der Geschichte und liest mit umso mehr Begeisterung weiter." },
        { t: "Eine Reise, die bleibt", tag: "Ein Abenteuer, acht spannende Kapitel.", d: "Jedes Kapitel bringt eine neue Geschichte, einen neuen Holzbausatz und eine weitere Spur zum Schatz — Vorfreude auf das nächste Kapitel inklusive." },
      ],
    },

    inside: {
      eyebrow: "Die Box",
      title: "Was steckt in der Box?",
      sub: "Alles für einen gemeinsamen Abend.",
      body: "In jeder Box: ein neues personalisiertes Kapitel und der passende Holzbausatz. Kapitel für Kapitel füllt sich die Mappe, die mit Kapitel 1 bei euch einzieht.",
      itemsHeading: "Inhalt der Box",
      items: [
        { n: "01", icon: "archive", t: "Die Kunstleder-Mappe", d: "Eine A5-Mappe aus Kunstleder, geprägt mit dem Namen eures Kindes — hier sammeln sich alle acht personalisierten Kapitel." },
        { n: "02", icon: "compass", t: "Die Schatzkarte", d: "Eine liebevoll illustrierte A2-Schatzkarte zeigt die ganze Reise — und wird Abenteuer für Abenteuer vervollständigt." },
        { n: "03", icon: "book", t: "Das Geschichtenkapitel", d: "Ein hochwertiger A5-Druck auf feinem Papier, gedruckt in Deutschland — mit dem Namen eures Kindes mitten in der Geschichte." },
        { n: "04", icon: "build", t: "Der Holzbausatz", d: "In jedem Kapitel ein anderer Bausatz: Kinder bauen die Erfindung, mit der Popcorn & Freddy das nächste Hindernis überwinden." },
        { n: "05", icon: "palette", t: "Farben & Pinsel", d: "Vier kinderfreundliche Farben und zwei Pinsel in jedem Kapitel — so bekommt jedes Werkstück seinen eigenen Look." },
        { n: "06", icon: "check", t: "Die Bauanleitung", d: "Illustrierte Schritt-für-Schritt-Anleitung in eurer Sprache — Bauen wird zum gemeinsamen Spiel." },
        { n: "07", icon: "star", t: "Der Abenteuer-Sticker", d: "Nach jedem bestandenen Abenteuer kommt der Kapitel-Sticker auf die Schatzkarte — der Fortschritt bis zum Schatz wächst sichtbar mit." },
      ],
    },

    chapters: {
      eyebrow: "Die komplette Reihe",
      title: "Kapitel für Kapitel zum verborgenen Schatz.",
      sub: "Die Geschichte baut Kapitel für Kapitel aufeinander auf. Startet mit dem ersten — neue Kapitel erscheinen Monat für Monat.",
      available: "Auf Lager",
      incl_ship: "sofort lieferbar",
      extras: "+ Schatzkarte + Ordner",
      notify: "Zum Start benachrichtigen",
      notify_ph: "deine@email.de",
      notify_ok: "Danke! Wir schreiben dir zum Start.",
      box_title: "Alle 8 Kapitel",
      box_sub: "Jeden Monat ein neuer Abend — sieh dir die ganze Reise an.",
      box_cta: "Zur Kapitel-Übersicht",
      back: "Zur Startseite",
      includes: "In der Box enthalten:",
      bullets: ["Buchkapitel", "Holzspielzeug-Bausatz", "Pinsel & 6 Farben", "Schatzkarte", "Schatzbuch zum Sammeln"],
      price_from: "ab",
      price: "39,90 €",
      cta: "In den Warenkorb",
      details: "Kapitel ansehen",
      gift_toggle: "Als Geschenk",
      gift_note: "Magische Geschenkverpackung mit Wachssiegel — gratis.",
      gift_msg: "Deine Nachricht (optional)",
      gift_msg_ph: "Für … zum Geburtstag",
      gift_date: "Wunsch-Lieferdatum (optional)",
      tag1: "Hier beginnt die Geschichte",
      tag2: "Neu",
      tag3: "Eltern-Favorit",
      locked_tag: "Bald enthüllt",
      locked_eyebrow: "Noch geheim",
      locked_title: "Wir lüften das\nGeheimnis bald.",
      locked_hint: "Popcorn & Freddy verraten noch nicht, wohin die Reise als nächstes geht — abonniere den Newsletter und sei dabei, wenn der Umschlag geöffnet wird.",
      locked_cta: "Benachrichtige mich",
      locked_release_2: "erscheint im Herbst",
      locked_release_3: "erscheint im Winter",
    },

    folder: {
      eyebrow: "Das Herzstück",
      title: "Das persönliche Schatzbuch eures Kindes",
      body: "Jede Familie erhält einmalig die hochwertige Abenteuer-Mappe aus Kunstleder — personalisiert mit dem Namen eures Kindes und einer liebevollen Lasergravur von Popcorn & Freddy. Hier sammeln sich Kapitel für Kapitel Schatzkarten, Erinnerungen, Sticker und kleine Abenteuer-Momente. Mit der Zeit wird daraus ein ganz persönliches Erinnerungsstück, das Kinder über Jahre begleitet.",
      feat1: "Hochwertiges Kunstleder",
      feat2: "Laser-gravierte Illustration",
      feat3: "Platz für alle 8 Kapitel",
      cta: "Mit dem ersten Kapitel sichern",
    },

    brand: {
      eyebrow: "Hinter der Marke",
      title: "Hallo, wir sind Martin und Jess.",
      p1: "Martin fliegt als Pilot um die Welt, Jess steht als Lehrerin jeden Tag vor Kindern. Dabei haben wir beide dasselbe gesehen: Gemeinsame Zeit ist das Kostbarste, was Familien haben.",
      p2: "Deshalb gibt es Popcorn & Freddy — kein weiteres Spielzeug zum Alleinspielen, sondern ein Abenteuer zum Vorlesen, Bauen, Bemalen und Erinnern.",
      p3: "",
      thanks: "Danke, dass ihr Teil unserer Geschichte seid.",
      sig: "Martin & Jess",
    },

    family: {
      eyebrow: "Für Familien",
      title: "Warum Familien Popcorn & Freddy lieben",
      sub: "Die schönsten Erinnerungen entstehen gemeinsam – Seite für Seite, Abend für Abend.",
      cards: [
        { icon: "📵", t: "Weniger Bildschirmzeit", d: "Eine Beschäftigung, die Kinder wirklich lieben – ganz ohne Tablet, Handy oder Fernseher. Stunden, die sich leicht und echt anfühlen." },
        { icon: "❤️", t: "Gemeinsame Zeit", d: "Lesen, bauen, malen und entdecken – zusammen. Aus einem Nachmittag wird ein Ritual, auf das sich die ganze Familie freut." },
        { icon: "🎨", t: "Kreativität & Fantasie", d: "Euer Kind macht mit: löst Rätsel, trifft Entscheidungen und erschafft mit den eigenen Händen etwas, auf das es stolz sein kann." },
        { icon: "🗄️", t: "Erinnerungen, die bleiben", d: "Das Abenteuer wächst Kapitel für Kapitel – und wird mit der Zeit zu einer Sammlung gemeinsamer Familienerinnerungen." },
      ],
      quote_a: "Manche Spielzeuge werden vergessen.",
      quote_b: "Gemeinsame Abenteuer bleiben.",
    },

    test: {
      eyebrow: "Was Familien schreiben",
      title: "Lieblingsbox seit der ersten Lieferung.",
      items: [
        { q: "Mein Sohn liest sonst nie — jetzt fragt er jeden Abend nach Popcorn. Und ich darf endlich mal wieder etwas mit Holz und Pinsel bauen.", n: "Lena, Mama von Theo (5)" },
        { q: "Wir haben die Kunstleder-Mappe mittlerweile bei jedem Oma-Besuch dabei. Die Karte mit der gravierten Eule ist ihr Lieblingsstück.", n: "Markus, Papa von Mira (6)" },
        { q: "Endlich ein Geschenk, das nicht nach drei Tagen im Regal verschwindet. Wir freuen uns jeden Monat aufs neue Kapitel.", n: "Antonia, Patentante von Jonna (4)" },
      ],
    },

    news: {
      eyebrow: "Bleib dabei",
      title: "Werde Teil der Schatzsuche.",
      body: "Neue Kapitel, kleine Bastel-Ideen für zu Hause und ab und zu eine Überraschung in dein Postfach. Kein Spam — versprochen mit Bären-Tatze.",
      placeholder: "deine@email.de",
      cta: "Mit dabei!",
      success: "Fast geschafft! Wir haben dir eine Bestätigungs-E-Mail geschickt — bitte klick den Link darin, dann bist du dabei. 🐻",
      consent: "Ja, schickt mir die Reisepost per E-Mail. Ich kann mich jederzeit über den Abmeldelink in jeder E-Mail wieder abmelden. Hinweise zur Verarbeitung in der",
      consent_link: "Datenschutzerklärung",
      consent_err: "Bitte bestätige kurz die Einwilligung.",
      gift: "10% Rabatt auf deine erste Box",
    },

    footer: {
      tag: "Geschichten zum Lesen — und zum Erleben.",
      shop: "Shop",
      about: "Über uns",
      help: "Hilfe",
      legal: "Rechtliches",
      l_chapters: "Alle Kapitel",
      l_folder: "Kunstleder-Mappe",
      l_gift: "Geschenkkarten",
      l_bundles: "Bundles",
      l_story: "Die Geschichte",
      l_team: "Das Atelier",
      l_press: "Presse",
      l_journal: "Journal",
      l_ship: "Versand & Rücksendung",
      l_faq: "FAQ",
      l_contact: "Kontakt",
      l_safety: "Sicherheit & Material",
      l_prodsafety: "Produktsicherheit",
      l_newsletter: "Newsletter",
      l_imp: "Impressum",
      l_priv: "Datenschutz",
      l_agb: "AGB",
      l_widerruf: "Widerruf",
      l_cookies: "Cookies",
      cookie_settings: "Cookie-Einstellungen",
      copy: "© 2026 Popcorn & Freddy · Mit viel Herz illustriert in Wien.",
    },
  },

  en: {
    nav: {
      story: "The Story",
      how: "How It Works",
      chapters: "All adventures",
      workshop: "Behind the Brand",
      folder: "The Box",
      family: "For Families",
      faq: "FAQ",
      contact: "Contact",
      shop: "Start the Adventure",
      mobile_cta: "Start the Adventure",
    },
    announce: "Only ~250 boxes a month · delivery in 2–3 business days",
    stickyCta: "Add to basket",
    stickyNote: "incl. VAT",
    stickyAll: "All chapters",
    trust: { ship: "Delivery in 2–3 business days", returns: "Shipping & returns", pay: ["PayPal", "Klarna", "SEPA"] },
    exit: { title: "Wait — 10% off your first box!", body: "Join the travel post and we'll send you 10% off your first chapter.", placeholder: "your@email.com", cta: "Claim discount", success: "Thank you! Your discount code is on its way. 🐻", dismiss: "No thanks" },
    bands: [
      { eyebrow: "Let's begin", title: "Ready to open the first chapter?", cta: "Discover chapter 1", href: "/produkt/kapitel-1-fluesterwald", note: "Only ~250 boxes a month · delivery in 2–3 business days" },
      { eyebrow: "Personalised", title: "Your child's name is already waiting on page 1.", cta: "Start the adventure", href: "#chapters", note: "Name in the book · engraved treasure folder" },
      { eyebrow: "8 chapters · 1 hidden treasure", title: "Start your first evening.", cta: "Discover chapter 1", href: "/produkt/kapitel-1-fluesterwald", note: "Plastic-free packaging · FSC wood" },
    ],

    hero: {
      eyebrow: "The great treasure hunt with Popcorn & Freddy",
      title_a1: "",
      title_a2: "An adventure to read, build and ",
      title_a3: "discover",
      title_a4: "",
      sub_a: "A personalised treasure hunt with real wooden toys to build, paint and discover. Together you join Popcorn & Freddy on their way to the treasure of friendship.",
      cta_primary: "Discover chapter 1",
      cta_secondary: "How it works",
      trust: [
        { icon: "⭐", label: "Your child's name in the book" },
        { icon: "🧩", label: "Real wooden toys to build" },
        { icon: "❤️", label: "Family time instead of screen time" },
        { icon: "🎈", label: "Ages 4 and up" },
      ],

      title_b1: "Build your",
      title_b2: " very own ",
      title_b3: "fairytale.",
      sub_b: "Every box is a chapter-world in wood: instructions, brushes, paints and a map to the next stop. Read, build, dream — together.",

      title_c1: "The treasure map",
      title_c2: " is calling.",
      sub_c: "Follow Popcorn and Freddy across 8 stops through the land of friendship. Each chapter is a new island, a new box, a new adventure.",
    },

    heroImg: {
      badge: "Personalised with your child's name",
      sub: "A personalised adventure storybook featuring your child’s name throughout all 8 chapters. Build a new wooden toy, solve puzzles, and uncover the hidden treasure with Popcorn & Freddy.",
      cards: [
        { icon: "user", t: "Your child's name in the book", d: "Personalised in every chapter." },
        { icon: "build", t: "A new invention in every chapter", d: "Build. Puzzle. Discover — together." },
        { icon: "heart", t: "A treasure hunt for the whole family", d: "8 adventures to the hidden treasure." },
      ],
      cta_primary: "Start the adventure",
      cta_secondary: "All Chapters",
      facts: "€39.90 · No subscription · Ages 4 and up",
      mini: [
        { icon: "screen", t: "Screen-free quality time" },
        { icon: "build", t: "Builds skills while having fun" },
        { icon: "book", t: "Your child is the hero" },
        { icon: "archive", t: "8 chapters. One treasure." },
      ],
      below: [
        { icon: "truck", t: "Around 250 a month", d: "Each one crafted by hand" },
        { icon: "shield", t: "Safe & non-toxic", d: "Made for children" },
        { icon: "gift", t: "The perfect gift", d: "For little adventurers" },
      ],
    },

    badge: {
      ages: "Ages 4 and up",
      eu: "Made in the EU",
      wood: "FSC wood",
      magic: "Packed with magic",
    },

    story: {
      eyebrow: "The Story",
      title: "A Story Your Child Becomes Part Of",
      body: "When Popcorn and Freddy find a mysterious treasure map, their greatest journey begins. But they can't find the hidden treasure alone. That's why your child's name is printed into every chapter and becomes part of the story. Together you'll experience 8 adventures that build on one another, construct helpful inventions, solve puzzles and guide Popcorn & Freddy all the way to the great treasure.",
      pop_name: "Popcorn",
      pop_role: "the curious bear",
      pop_quote: "\"What's in the next chapter?\"",
      pop_desc: "Curious, clever and always hunting for the next clue.",
      fred_name: "Freddy",
      fred_role: "the clever fox",
      fred_quote: "\"I have a plan!\"",
      fred_desc: "Smart, brave and never short of an idea.",
      peter_name: "Your child",
      peter_role: "The hero of the adventure",
      peter_quote: "\"Which colour shall we pick?\"",
      peter_desc: "Their name is in every chapter — the book becomes their own treasure hunt.",
    },

    how: {
      eyebrow: "Step by step",
      title: "How it works",
      tagline: "Unpack. Read. Build. Keep.",
      sub: "From the first click to the sticker on the treasure map — this is how every chapter works.",
      steps: [
        { n: "01", icon: "pen", t: "Order & tell us the name", d: "You order the first chapter and tell us your child's name. That's all it takes." },
        { n: "02", icon: "gift", t: "The personalised box arrives", d: "Inside: the folder with your child's name on it, the big treasure map — and the chapter where your child is part of the story." },
        { n: "03", icon: "book", t: "Read together", d: "You read the story aloud — or your child reads it to you. Popcorn & Freddy take them along on the journey." },
        { n: "04", icon: "build", t: "Solve the riddle & build", d: "Mid-chapter, Popcorn & Freddy ask for help: a riddle needs solving and a tool needs building from the wooden kit — it's the only way past the chapter's obstacle." },
        { n: "05", icon: "palette", t: "Paint & decorate", d: "With the included brush and child-friendly paints, every piece gets its own look." },
        { n: "06", icon: "archive", t: "Collect & stick", d: "The chapter goes into the personal folder and a sticker goes on the treasure map — so you can see how far the journey has come." },
      ],
    },

    map: {
      eyebrow: "The journey",
      title: "8 adventures. One hidden treasure.",
      sub: "From the Whispering Woods to the mysterious cave – every chapter tells a new adventure. Together you help Popcorn & Freddy, build inventions for the journey and follow the treasure map step by step to the hidden treasure.",
      poke: "Tip: tap the stops!",
    },

    why: {
      eyebrow: "Why parents love it",
      title: "Create memories they’ll remember for a lifetime.",
      sub: "Every chapter brings your family together to read, build, paint and solve puzzles — while your child becomes the hero of their own personalised adventure.",
      items: [
        { t: "Screen-Free Quality Time", tag: "Create meaningful moments together.", d: "Instead of passive screen time, children and parents read, build and solve puzzles side by side, creating lasting memories." },
        { t: "Learning Through Play", tag: "Builds creativity, problem-solving and fine motor skills.", d: "Every chapter combines storytelling, construction and puzzles, encouraging children to think, create and learn naturally while having fun." },
        { t: "Your Child Is the Hero", tag: "A truly personalised adventure.", d: "Your child's name appears throughout all eight chapters, making them an active part of the story and increasing engagement and motivation to read." },
        { t: "A Journey That Lasts", tag: "One adventure, eight exciting chapters.", d: "Each chapter introduces a new story, a new wooden toy to build and another clue towards the hidden treasure, creating anticipation and encouraging children to keep reading and exploring." },
      ],
    },

    inside: {
      eyebrow: "The box",
      title: "What's inside the box?",
      sub: "Everything for one evening together.",
      body: "Every box holds a new personalised story chapter and its matching wooden toy kit. Chapter by chapter, the folder that arrives with Chapter 1 fills up.",
      itemsHeading: "What's in the box",
      items: [
        { n: "01", icon: "archive", t: "The faux leather folder", d: "An A5 faux leather folder embossed with your child's name — made to collect all eight personalised story chapters." },
        { n: "02", icon: "compass", t: "The treasure map", d: "A beautifully illustrated A2 treasure map showing the whole journey — completed adventure by adventure." },
        { n: "03", icon: "book", t: "The story chapter", d: "A premium A5 print on fine paper, printed in Germany — with your child's name woven through the story." },
        { n: "04", icon: "build", t: "The wooden toy kit", d: "A different construction kit in every chapter: children build the invention that helps Popcorn & Freddy past the next obstacle." },
        { n: "05", icon: "palette", t: "Paints & brushes", d: "Four child-friendly paint colours and two brushes in every chapter — so each creation gets its own look." },
        { n: "06", icon: "check", t: "The assembly guide", d: "An illustrated step-by-step guide in your language — building becomes part of the game." },
        { n: "07", icon: "star", t: "The adventure sticker", d: "After each completed adventure, the chapter sticker goes on the treasure map — progress toward the treasure grows in plain sight." },
      ],
    },

    chapters: {
      eyebrow: "The complete series",
      title: "Chapter by chapter to the hidden treasure.",
      sub: "The story builds chapter by chapter. Start with the first — new chapters arrive month by month.",
      available: "In stock",
      incl_ship: "ready to ship",
      extras: "+ Treasure map + Folder",
      notify: "Notify me at release",
      notify_ph: "your@email.com",
      notify_ok: "Thanks! We'll email you at release.",
      box_title: "All 8 chapters",
      box_sub: "A new evening every month — see the whole journey.",
      box_cta: "See every chapter",
      back: "Back to home",
      includes: "Inside the box:",
      bullets: ["Book chapter", "Wooden toy kit", "Brush & 6 paints", "Treasure map", "Treasure book to collect in"],
      price_from: "from",
      price: "€39.90",
      cta: "Add to basket",
      details: "View chapter",
      gift_toggle: "As a gift",
      gift_note: "Magical gift wrapping with wax seal — free.",
      gift_msg: "Your message (optional)",
      gift_msg_ph: "For … on their birthday",
      gift_date: "Preferred delivery date (optional)",
      tag1: "Where the story starts",
      tag2: "New",
      tag3: "Parent pick",
      locked_tag: "Coming soon",
      locked_eyebrow: "Still a secret",
      locked_title: "The mystery\nunfolds soon.",
      locked_hint: "Popcorn & Freddy aren't telling where the journey heads next — join the newsletter and be there when the envelope is opened.",
      locked_cta: "Notify me",
      locked_release_2: "out this autumn",
      locked_release_3: "out this winter",
    },

    folder: {
      eyebrow: "The heart of it all",
      title: "Your child's very own treasure book",
      body: "Every family receives a one-time adventure folder made of faux leather — personalised with your child's name and a lovingly laser-engraved illustration of Popcorn & Freddy. Chapter by chapter it fills with treasure maps, memories, stickers and little adventure moments. Over time it grows into a deeply personal keepsake that stays with kids for years.",
      feat1: "Premium faux leather",
      feat2: "Laser-engraved illustration",
      feat3: "Room for all 8 chapters",
      cta: "Get it with chapter one",
    },

    brand: {
      eyebrow: "Behind the Brand",
      title: "Hi, we’re Martin and Jess.",
      p1: "Martin flies around the world as a pilot; Jess teaches children every day. We both kept seeing the same thing: time together is the most precious thing a family has.",
      p2: "That’s why Popcorn & Freddy exists — not another toy to play with alone, but an adventure to read, build, paint and remember together.",
      p3: "",
      thanks: "Thank you for being part of our story.",
      sig: "Martin & Jess",
    },

    family: {
      eyebrow: "For families",
      title: "Why families love Popcorn & Freddy",
      sub: "The best memories are made together – page by page, evening by evening.",
      cards: [
        { icon: "📵", t: "Less screen time", d: "Something children genuinely love – with no tablet, phone or TV in sight. Hours that feel light, slow and real." },
        { icon: "❤️", t: "Time together", d: "Reading, building, painting and discovering – together. An afternoon becomes a ritual the whole family looks forward to." },
        { icon: "🎨", t: "Creativity & imagination", d: "Your child takes part: solving puzzles, making choices and creating something with their own hands to be proud of." },
        { icon: "🗄️", t: "Memories that last", d: "The adventure grows chapter by chapter – and becomes a collection of shared family memories over time." },
      ],
      quote_a: "Some toys are forgotten.",
      quote_b: "Shared adventures stay.",
    },

    test: {
      eyebrow: "What families say",
      title: "Favourite box since the very first delivery.",
      items: [
        { q: "My son never reads — now he asks for Popcorn every single night. And I finally get to build something with wood and paint again.", n: "Lena, mum of Theo (5)" },
        { q: "We take the faux leather folder to every grandma visit. The card with the engraved owl is her absolute favourite.", n: "Markus, dad of Mira (6)" },
        { q: "Finally a gift that doesn't disappear into the shelf after three days. We look forward to every new chapter.", n: "Antonia, godmother of Jonna (4)" },
      ],
    },

    news: {
      eyebrow: "Stay close",
      title: "Join the treasure hunt.",
      body: "New chapters, little crafting ideas for home and the occasional surprise in your inbox. No spam — bear-paw promise.",
      placeholder: "your@email.com",
      cta: "I'm in!",
      success: "Almost there! We’ve sent you a confirmation email — please click the link inside to complete your sign-up. 🐻",
      consent: "Yes, send me the travel post by email. I can unsubscribe at any time via the link in every email. Details on processing in the",
      consent_link: "privacy policy",
      consent_err: "Please confirm your consent first.",
      gift: "10% off your first box",
    },

    footer: {
      tag: "Stories to read — and to live.",
      shop: "Shop",
      about: "About",
      help: "Help",
      legal: "Legal",
      l_chapters: "All chapters",
      l_folder: "Faux leather folder",
      l_gift: "Gift cards",
      l_bundles: "Bundles",
      l_story: "The story",
      l_team: "The studio",
      l_press: "Press",
      l_journal: "Journal",
      l_ship: "Shipping & returns",
      l_faq: "FAQ",
      l_contact: "Contact",
      l_safety: "Safety & materials",
      l_prodsafety: "Product safety",
      l_newsletter: "Newsletter",
      l_imp: "Imprint",
      l_priv: "Privacy",
      l_agb: "Terms",
      l_widerruf: "Right of withdrawal",
      l_cookies: "Cookies",
      cookie_settings: "Cookie settings",
      copy: "© 2026 Popcorn & Freddy · Lovingly illustrated in Vienna.",
    },
  },
};

window.COPY = COPY;
